# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'girisEkrani.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(484, 478)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.le_kullaniciAdi = QtWidgets.QLineEdit(self.centralwidget)
        self.le_kullaniciAdi.setObjectName("le_kullaniciAdi")
        self.verticalLayout.addWidget(self.le_kullaniciAdi)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.pb_giris = QtWidgets.QPushButton(self.centralwidget)
        self.pb_giris.setObjectName("pb_giris")
        self.verticalLayout.addWidget(self.pb_giris)
        self.pb_kaydol = QtWidgets.QPushButton(self.centralwidget)
        self.pb_kaydol.setObjectName("pb_kaydol")
        self.verticalLayout.addWidget(self.pb_kaydol)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 484, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Giris Ekranı"))
        self.label.setText(_translate("MainWindow", "ALTAY TEKNİK SERVİS"))
        self.le_kullaniciAdi.setPlaceholderText(_translate("MainWindow", "Kullanıcı adı giriniz..."))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Şifrenizi giriniz..."))
        self.pb_giris.setText(_translate("MainWindow", "Giriş"))
        self.pb_kaydol.setText(_translate("MainWindow", "Kayıt"))
