# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'parcaStok_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_parca_stok(object):
    def setupUi(self, parca_stok):
        parca_stok.setObjectName("parca_stok")
        parca_stok.resize(529, 636)
        self.centralwidget = QtWidgets.QWidget(parca_stok)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pb_parcaSil = QtWidgets.QPushButton(self.centralwidget)
        self.pb_parcaSil.setObjectName("pb_parcaSil")
        self.horizontalLayout.addWidget(self.pb_parcaSil)
        self.pb_parcaEkle = QtWidgets.QPushButton(self.centralwidget)
        self.pb_parcaEkle.setObjectName("pb_parcaEkle")
        self.horizontalLayout.addWidget(self.pb_parcaEkle)
        self.pb_parcaTableGuncelle = QtWidgets.QPushButton(self.centralwidget)
        self.pb_parcaTableGuncelle.setObjectName("pb_parcaTableGuncelle")
        self.horizontalLayout.addWidget(self.pb_parcaTableGuncelle)
        self.pb_parcastokAnamenu = QtWidgets.QPushButton(self.centralwidget)
        self.pb_parcastokAnamenu.setObjectName("pb_parcastokAnamenu")
        self.horizontalLayout.addWidget(self.pb_parcastokAnamenu)
        self.verticalLayout.addLayout(self.horizontalLayout)
        parca_stok.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parca_stok)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 529, 26))
        self.menubar.setObjectName("menubar")
        parca_stok.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parca_stok)
        self.statusbar.setObjectName("statusbar")
        parca_stok.setStatusBar(self.statusbar)

        self.retranslateUi(parca_stok)
        QtCore.QMetaObject.connectSlotsByName(parca_stok)

    def retranslateUi(self, parca_stok):
        _translate = QtCore.QCoreApplication.translate
        parca_stok.setWindowTitle(_translate("parca_stok", "Parça Stoğu"))
        self.label.setText(_translate("parca_stok", "Parça Stoğu"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("parca_stok", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("parca_stok", "Parça Adı"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("parca_stok", "Fiyat"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("parca_stok", "Parça Adeti"))
        self.pb_parcaSil.setText(_translate("parca_stok", "Parça Sil"))
        self.pb_parcaEkle.setText(_translate("parca_stok", "Parça Ekle"))
        self.pb_parcaTableGuncelle.setText(_translate("parca_stok", "Güncelle"))
        self.pb_parcastokAnamenu.setText(_translate("parca_stok", "Ana menü"))
