# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'parcaStokEkle_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(308, 331)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit_stokParcaadi = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_stokParcaadi.setObjectName("lineEdit_stokParcaadi")
        self.horizontalLayout.addWidget(self.lineEdit_stokParcaadi)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.spinBox_stokParcafiyat = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_stokParcafiyat.setMaximum(9999)
        self.spinBox_stokParcafiyat.setObjectName("spinBox_stokParcafiyat")
        self.horizontalLayout_3.addWidget(self.spinBox_stokParcafiyat)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.spinBox_stokParcaadet = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_stokParcaadet.setMaximum(9999)
        self.spinBox_stokParcaadet.setObjectName("spinBox_stokParcaadet")
        self.horizontalLayout_2.addWidget(self.spinBox_stokParcaadet)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.pushButton_kaydet = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_kaydet.setObjectName("pushButton_kaydet")
        self.verticalLayout.addWidget(self.pushButton_kaydet)
        self.pushButton_Anamenu = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Anamenu.setObjectName("pushButton_Anamenu")
        self.verticalLayout.addWidget(self.pushButton_Anamenu)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 308, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Stok Parca Ekle"))
        self.label.setText(_translate("MainWindow", "Stok Parca Ekle"))
        self.label_2.setText(_translate("MainWindow", "Parca Adı:"))
        self.label_4.setText(_translate("MainWindow", "Parca Fiyat:"))
        self.label_3.setText(_translate("MainWindow", "Adet :"))
        self.pushButton_kaydet.setText(_translate("MainWindow", "Kaydet"))
        self.pushButton_Anamenu.setText(_translate("MainWindow", "Ana Menü"))
